TRUNCATE TABLE quiz_results RESTART IDENTITY CASCADE;
TRUNCATE TABLE performance_history RESTART IDENTITY CASCADE;
TRUNCATE TABLE quiz_questions RESTART IDENTITY CASCADE;
TRUNCATE TABLE students RESTART IDENTITY CASCADE;